Update add/update methods of Collection to convert non-valid input types
(Noticed when trying to add bool/NoneType)

redis.exceptions.DataError: Invalid input of type: 'NoneType'. Convert to a bytes, string, int or float first.